{% set name = "gulpio" %}
{% set version = "540.66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7ceb4d8115b28ed22b6572d06797df417c2a3560d4efb050b489dbba5e27cdb

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - opencv
    - tqdm
    - sh
    - docopt
    - pillow
    - numpy
    - jinja2

test:
  requires:
    - python
  imports:
    - gulpio
  commands:
    - gulp_image_folder --help
    - gulp_sanity_check --help

about:
  home: https://github.com/TwentyBN/GulpIO
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Binary storage format for deep learning on videos.
  doc_url: https://github.com/TwentyBN/GulpIO
  dev_url: https://github.com/TwentyBN/GulpIO

extra:
  recipe-maintainers:
    - willprice
