travis:
  secure:
    BINSTAR_TOKEN: GqEbUn13cY+EqEL11eh/Hb70Y4Ol0/LHpShQbwYH6onmLobvluI2vhdL2IoTNxT7k3ohbYFHQ3V3VKk1AmWUvKO1lVQ74NKrt6kuFQOVTZHRxKc+NQWOULtD2lcIbszOScldmxBdKpnRI5G4G91kRvZmJqEiopQRgTlKwtTV9JPexYtLjEGGWWOcvEl5lDhHcbODFRIjZj+ZJlz/5d2TcnXeUkKrLTRjyqVGXguyuZJCj7Ac8B79lBm+Zs1rWiHGCGC1J8gg+OolftLHZthh0HzCA1dnniXkC3WOU71/tENFEliyAWgsp5Q8ZeJUu0IaeUJw0hc2kUzb64+zNiEo0D0GsJAv1DLD5JuAR55Mygy3HkUvuFFnzbd+qAl+4ztn/C0K7jD3LzniBof0kmjUdbR5l8HuKg2tMCm/5I7vCocfX807DVwUiOpci/A6CxsQNYy3m4f5WRkrLo45ehmtmITpsaTBJf9Fe3k3q1rGJeglUxQ40MmNNx/8S9E49g0406z/28tIFJYqdSp9Z1plPBxOrLnoLoaL+WCPZTv75gAqxTljC4BEWAyxOQ4nf4k0SJnswiOGs+H5+ZdxPWjOf6NP7XSiEV/OR7OOcvcN0vYK4YSXKc4Ko/ToP2RbPOAPcsexohq6LV9un3LK9u7nuBHVlUub+v/AR6bQnVMEZbg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
